### ISSUE TITLE
Deploy as Application Bundle (macOS)

### ISSUE THREAD

**Issue by pastewka** [livMatS/dtool-lookup-gui#120]
On macOS, we should deploy as an application bundle to avoid the slow extraction phase of the single binary we have now. We should also package into an Apple Disk Image (.dmg) rather than as a ZIP file.

**Comment by pastewka** [comment]
This may fix #106

**Comment by pastewka** [comment]
This may help: https://www.pythonguis.com/tutorials/packaging-pyqt5-applications-pyinstaller-macos-dmg/

**Comment by jotelha** [comment]
Yes, that helped, needed minor modifications to the pyinstaller spec files and build workflows, see https://github.com/livMatS/dtool-lookup-gui/pull/121. The zipped .app bundle is still about the same size as before, but when unpacked the .app is about 400 MB...
