### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by pastewka** [livMatS/dtool-lookup-gui#122]
Add application icon and make sure deployed bundles use this icon

**Comment by jotelha** [comment]
On Ubuntu 20.04 (GNOME), the "large" icon with zeros and ones looks good in the launcher, but not as great in the dock, i.e. 
![image](https://user-images.githubusercontent.com/1868344/158056540-6dc49675-b9a9-4afc-837b-e69a4edd5776.png)

vs

![image](https://user-images.githubusercontent.com/1868344/158056073-7da7cf5b-73cb-4073-8183-113687c22962.png)

The format specification of those .desktop launcher files are apparently part of the freedesktop.org project, https://specifications.freedesktop.org/desktop-entry-spec/latest/, and I don't see any possibility to specify different icons for different sizes. 

Maybe use the blank, white d here?

**Comment by pastewka** [comment]
Yes use the blank one

**Comment by pastewka** [comment]
Can this be closed?
