### ISSUE TITLE
macOS binary does not work

### ISSUE THREAD

**Issue by pastewka** [livMatS/dtool-lookup-gui#145]
The current macOS binary does not work (at least on Monterey). The App-Bundle does not have an application icon.

**Comment by jotelha** [comment]
The downloaded .app works when extracting from the internal intermediate .tar artifact, i.e. ttps://github.com/livMatS/dtool-lookup-gui/suites/5851967662/artifacts/196983376, looks like the repackaging for release to .zip somehow corrupts the .app folder (below https://github.com/livMatS/dtool-lookup-gui/blob/master/.github/workflows/build-and-publish.yml#L86), will look into that later.

**Comment by pastewka** [comment]
Can you create a DMG file rather than a ZIP?

See here: https://www.recitalsoftware.com/blogs/148-howto-build-a-dmg-file-from-the-command-line-on-mac-os-x

**Comment by jotelha** [comment]
This is a dmg, https://github.com/livMatS/dtool-lookup-gui/suites/5962662591/artifacts/204875824 packaged with https://github.com/create-dmg/create-dmg. The PyQt5/Pyinstaller/macOS guide https://www.pythonguis.com/tutorials/packaging-pyqt5-applications-pyinstaller-macos-dmg/ was quite useful, but I still struggle to get the mac OS icons right.

**Comment by jotelha** [comment]
Ok, solved with https://github.com/livMatS/dtool-lookup-gui/commit/8059cfbc311ada8955d204912458e2a01d20e5f4.
