### ISSUE TITLE
Installation via dmg on MACOSX Monterey

### ISSUE THREAD

**Issue by sannant** [livMatS/dtool-lookup-gui#170]
![grafik](https://user-images.githubusercontent.com/40853209/167458746-b46ccd6e-68cc-430a-a5eb-e094499095ed.png)

**Comment by sannant** [comment]
I tried without and with installing the requirements before

**Comment by jotelha** [comment]
Was that the latest dmg (0.6.1) from https://github.com/livMatS/dtool-lookup-gui/releases/latest ? I will have to check that tomorrow

**Comment by sannant** [comment]
Yes. As far as I understand that is he only dmg available, right ?

**Comment by sannant** [comment]
Work around: 

Call 
/Applications/dtool-lookup-gui.app/Contents/MacOS/dtool-lookup-gui

from the commandline

**Comment by jotelha** [comment]
Hm same issue on a macOS 11.6.4 machine, but the mac mini with 12.3.1 (same version as yours) I use for testing doesn't complain. I wonder whether that is somehow related to macOS code signing (https://pyinstaller.org/en/stable/feature-notes.html#macos-binary-code-signing). Might need someone's help who understands that somehow.

**Comment by sannant** [comment]
Or did you somehow deactivate some of these annoying security checks of the applications on the MacMini ? 

Anyway all that is not not critical for me.

**Comment by jotelha** [comment]
https://github.com/livMatS/dtool-lookup-gui/commit/29d5d6cd3b2f856d8333a1db2a82feaf5c7d265e adds a note on that workaround in the README, on the long run we might want to invest those 99 $ to become an apple-verified developer.

**Comment by sannant** [comment]
Yes works
