### ISSUE TITLE
dtool-lookup-gui-0.6.2-linux Starting Issue

### ISSUE THREAD

**Issue by ashdriod** [livMatS/dtool-lookup-gui#213]
GLib-GIO-ERROR **: 13:10:44.889: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
and I'm using wayland

**Comment by jotelha** [comment]
Likely related to x11 vs wayland issue, https://askubuntu.com/questions/1411216/siril-appimage-returns-glib-gio-error-missing-antialiasing-key-ubuntu-22-04

**Comment by jotelha** [comment]
Documented in https://github.com/livMatS/dtool-lookup-gui/commit/3df25573302b68b0e5f63170b885b2696d5d4fb2
