### ISSUE TITLE
Authentication failure is obscured by HTML parsing error.

### ISSUE THREAD

**Issue by wgnoehring** [livMatS/dtool-lookup-gui#24]
I have a problem where `dtool_lookup_gui`  is able to connect to the lookup server, but then authentication fails in a second step. 
The following message is displayed in the top bar: 
```0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf8', url=URL( <loopup server url>)```

The problem seems to be `server_config`  in  `MainApplication.py`. There is some kind of authentication failure. Instead of a 
valid configuration, the variable is set to the following HTML code string: 
```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>401 Unauthorized</title> <h1>Unauthorized</h1> <p>The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.</p>```

It seems that failure to parse this HTML code leads to the aforementioned message in the top bar, which obscures the problem.

Note that if I simply set a wrong username or password, `dtool_lookup_gui` shows `Authentication failed` in the info bar at the top.

**Comment by wgnoehring** [comment]
The authentication problem is likely just a problem with my account, but the parsing error obscures the problem. The HTML error message is never shown on the terminal or in the UI.

**Comment by wgnoehring** [comment]
The following error message is printed on the terminal:

```(__main__.py:1126174): Gtk-WARNING **: 19:08:11.219: Overriding tab label for notebook
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SignalHandler.connect() done, defined at /home/wnoehring/.local/lib/python3.9/site-packages/dtool_lookup_gui/MainApplication.py:343> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/home/wnoehring/.local/lib/python3.9/site-packages/dtool_lookup_gui/MainApplication.py", line 362, in connect
    self._refresh_results()
  File "/home/wnoehring/.local/lib/python3.9/site-packages/dtool_lookup_gui/MainApplication.py", line 240, in _refresh_results
    f"{self.server_config['version']}")
TypeError: string indices must be integers
```

**Comment by pastewka** [comment]
Is this still an issue. @jotelha added a log window that may show more information.
