### ISSUE TITLE
Deploy for Linux, Windows and Mac via CI

### ISSUE THREAD

**Issue by pastewka** [livMatS/dtool-lookup-gui#51]
It would be good to create binary releases automatically in CI. We should explore [pyinstaller](https://www.pyinstaller.org/) to do this. This worked at least to create Windows release for earlier versions.

**Comment by jotelha** [comment]
For Windows-CI via MSYS2/MinGW: https://www.msys2.org/docs/ci/
With PyInstaller, we will need to "enable" `multiprocessing.freeze_support()`, see https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by jotelha** [comment]
Started work on automatic linux deployment in https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/64

**Comment by jotelha** [comment]
Automatic deployment for Linux (Ubuntu) and Windows works alright, MacOS should be possible in a similar manner on github, see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#about-github-hosted-runners, or https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/

**Comment by pastewka** [comment]
Is looking good. I need to grab one of our Macs to test Mac deployment with pyinstaller.

**Comment by jotelha** [comment]
MacOS x84_64 automatic build working, witch to "fat" binary ASAP, see https://pyinstaller.readthedocs.io/en/latest/feature-notes.html#macos-multi-arch-support, https://github.com/pyinstaller/pyinstaller/issues/5315#issuecomment-971341261

**Comment by pastewka** [comment]
Don't worry about the universal binary. I predict that this will become a pain in the neck as the whole GTK toolchain needs to be universal as well.

**Comment by jotelha** [comment]
Ok, then I will close this issue, we deploy on MacOS >= 10.15, Linux (Ubuntu >= 20.04), and Windows 10.
