### ISSUE TITLE
Version information dialog

### ISSUE THREAD

**Issue by pastewka** [livMatS/dtool-lookup-gui#84]
We should add a dialog that display the dtool versions, i.e. of

* `dtool-lookup-gui`
* `dtoolcore`
* `dtool-s3`
* `dtool-smb`

and potentially any other installed plugin. (Not sure if dtool has a mechanism to enumerate those.)

This will be useful in particular to check for a binary release which dtool version that one is using.

**Comment by jotelha** [comment]
On the CLI,

```console
$ dtool --version
dtool, version 

Base:
dtoolcore, version 3.18.1
dtool-cli, version 0.7.1

Storage brokers:
file, dtoolcore, version 3.18.1
s3, dtool-s3, version 0.13.0
irods, dtool-irods, version 0.10.0
ecs, dtool-ecs, version 0.5.0
https, dtool-http, version 0.5.0
http, dtool-http, version 0.5.0
symlink, dtool-symlink, version 0.3.0
smb, dtool-smb, version 0.1.0

Plugins:
dtool-annotation, version 0.1.0
dtool-sync, version 0.1.dev25
dtool-create, version 0.23.4
dtool-config, version 0.4.1
dtool-tag, version 0.1.0
dtool-lookup-client, version 0.1.0
dtool-overlay, version 0.3.0
dtool-info, version 0.16.2
```

**Comment by pastewka** [comment]
Okay, yes exactly this information should be in the dialog (plus the GUI version)

**Comment by jotelha** [comment]
What about this one?

![image](https://user-images.githubusercontent.com/1868344/156033432-9ecbf75f-54e5-4df5-809c-0625645d90f8.png)

**Comment by pastewka** [comment]
Looks good.

What does the "dtool, version" on top mean? The URLs at the bottom are cut off, maybe link some text without showing the URL

**Comment by jotelha** [comment]
The URLs aren't cut off anywhere I have looked at, does that happen locally for you?

**Comment by pastewka** [comment]
At the bottom of your screenshot they look like they are cut but they may not be.
