### ISSUE TITLE
Text search query does not show the datasets in the lookup server

### ISSUE THREAD

**Issue by mtelewa** [livMatS/dtool-lookup-gui#97]
**Summary**
Consider the test server provided [here](https://github.com/livMatS/RDM-Wiki-public/blob/master/rdm/dtool/src/020_gui/005_quick_start.md). In the search bar, a query by the username (as an example), in simple text, does not show any datasets in the lookup server. The dataset was created more than 48 hours ago.
**Actual Outcome**
0 datasets in the Lookup server
**Expected Outcome**
1 datasets in the Lookup server
**dtool-lookup-gui version**
0.4.5

**Comment by jotelha** [comment]
Works for me here, 

![image](https://user-images.githubusercontent.com/1868344/156146847-448de38f-a61b-4a24-88ac-bbe5ece21c99.png)

**Comment by jotelha** [comment]
Or with
![image](https://user-images.githubusercontent.com/1868344/156147012-7cb357d0-578b-40b5-8e8b-0294d663bc7f.png)

or with

![image](https://user-images.githubusercontent.com/1868344/156147145-b33f32cf-db47-48f3-9c1f-6a9a9329ed2a.png)

**Comment by jotelha** [comment]
with the reference settings

![image](https://user-images.githubusercontent.com/1868344/156147311-966b84ad-e718-4705-a4ee-f0bd1b5efaf4.png)

**Comment by mtelewa** [comment]
Issue resolved with the correct lookup server configuration.
